[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/.mjs"
  [headers.values]
    "Content-Type" = "application/javascript"

[[redirects]]
  from = "/api/"
  to = "https://rumbox-pescar.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/img/"
  to = "https://rumbox-pescar.onrender.com/img/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200