[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    "Content-Type" = "application/javascript"

[[redirects]]
  from = "/api/*"
  to = "https://rumbox-pescar.onrender.com/:splat"
  status = 200
  force = true